// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS5o5tD5cEPj2tlOf6Un-Apb4y87LYCb0',
    appId: '1:689422627040:web:8f42c84e9f2477c19f6085',
    messagingSenderId: '689422627040',
    projectId: 'stock-predictor-c1437',
    authDomain: 'stock-predictor-c1437.firebaseapp.com',
    storageBucket: 'stock-predictor-c1437.appspot.com',
    measurementId: 'G-S1887H8FE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeT1v0rKALdSADg88KemoaianU514mfGg',
    appId: '1:689422627040:android:d7c1d3fd33fb9c6c9f6085',
    messagingSenderId: '689422627040',
    projectId: 'stock-predictor-c1437',
    storageBucket: 'stock-predictor-c1437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOWJidNGX-uZLYzq-TH6XSgN507pZpMQ',
    appId: '1:689422627040:ios:68d4b9e9f073d7129f6085',
    messagingSenderId: '689422627040',
    projectId: 'stock-predictor-c1437',
    storageBucket: 'stock-predictor-c1437.appspot.com',
    iosClientId: '689422627040-c7vvm5cb2iidjo5qgq2lq61f8ok3tcas.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockPredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmOWJidNGX-uZLYzq-TH6XSgN507pZpMQ',
    appId: '1:689422627040:ios:969b7b846f603a979f6085',
    messagingSenderId: '689422627040',
    projectId: 'stock-predictor-c1437',
    storageBucket: 'stock-predictor-c1437.appspot.com',
    iosClientId: '689422627040-bma36pm9t8u1hpuoih5jfjhub6mbcol2.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockPredictor.RunnerTests',
  );
}
